//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftAML_UpperLinkAPI.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class account_information_upload
    {
        public long id { get; set; }
        public string account_number { get; set; }
        public string account_branch { get; set; }
        public string account_name { get; set; }
        public string client_number { get; set; }
        public string account_currency_code { get; set; }
        public string account_type { get; set; }
        public Nullable<System.DateTime> account_opened_date { get; set; }
        public string account_closed_date { get; set; }
        public string account_status_code { get; set; }
        public string account_beneficiary { get; set; }
        public Nullable<decimal> account_balance { get; set; }
        public string entity_name { get; set; }
        public string entity_incorporation_number { get; set; }
        public string entity_business { get; set; }
        public string entity_phone_contact_type { get; set; }
        public string entity_phone_type { get; set; }
        public string entity_phone_number { get; set; }
        public string entity_address_type { get; set; }
        public string entity_address { get; set; }
        public string entity_city { get; set; }
        public string entity_state { get; set; }
        public string entity_country_code { get; set; }
        public string entity_email { get; set; }
        public string uploader { get; set; }
        public Nullable<System.DateTime> uploaded { get; set; }
        public string batch_number { get; set; }
    }
}
