//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftAML_UpperLinkAPI.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class PepList
    {
        public long Id { get; set; }
        public string UniqueIdentifier { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string OtherNames { get; set; }
        public string Titles { get; set; }
        public string AKA { get; set; }
        public string Sex { get; set; }
        public string Age { get; set; }
        public string PresentPosition { get; set; }
        public string PreviousPosition { get; set; }
        public string PePClassification { get; set; }
        public string OfficialAddress { get; set; }
        public string Profession { get; set; }
        public string ResidentialAddress { get; set; }
        public string StateofOrigin { get; set; }
        public string Spouse { get; set; }
        public string Children { get; set; }
        public string Sibling { get; set; }
        public string Parents { get; set; }
        public string MothersMaiden { get; set; }
        public string Associates { get; set; }
        public string BusinessInterest { get; set; }
        public string Bankers { get; set; }
        public string AccountDetails { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string PlaceofBirth { get; set; }
        public string PressReport { get; set; }
        public Nullable<System.DateTime> DateofReport { get; set; }
        public string AdditionalInformation { get; set; }
        public string EmailAddress { get; set; }
        public string Telephone { get; set; }
        public string MeansID { get; set; }
    }
}
