//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftAML_UpperLinkAPI.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAPILog
    {
        public long id { get; set; }
        public string Endpoint { get; set; }
        public string PayLoad { get; set; }
        public string Message { get; set; }
    }
}
