//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftAML_UpperLinkAPI.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_information_upload
    {
        public long id { get; set; }
        public string t_account_number { get; set; }
        public string t_trans_number { get; set; }
        public string t_location { get; set; }
        public string transaction_description { get; set; }
        public Nullable<System.DateTime> t_date { get; set; }
        public string t_teller { get; set; }
        public string t_authorized { get; set; }
        public string t_late_deposit { get; set; }
        public Nullable<System.DateTime> t_date_posting { get; set; }
        public Nullable<System.DateTime> t_value_date { get; set; }
        public string t_transmode_code { get; set; }
        public Nullable<decimal> t_amount_local { get; set; }
        public string t_source_client_type { get; set; }
        public string t_source_type { get; set; }
        public string t_source_funds_code { get; set; }
        public string t_source_currency_code { get; set; }
        public Nullable<decimal> t_source_foreign_amount { get; set; }
        public Nullable<decimal> t_source_exchange_rate { get; set; }
        public string t_source_country { get; set; }
        public string t_source_institution_code { get; set; }
        public string t_source_institution_name { get; set; }
        public string t_source_account_number { get; set; }
        public string t_source_account_name { get; set; }
        public string t_source_person_first_name { get; set; }
        public string t_source_person_last_name { get; set; }
        public string t_source_entity_name { get; set; }
        public string t_dest_client_type { get; set; }
        public string t_dest_type { get; set; }
        public string t_dest_funds_code { get; set; }
        public string t_dest_currency_code { get; set; }
        public Nullable<decimal> t_dest_foreign_amount { get; set; }
        public Nullable<decimal> t_dest_exchange_rate { get; set; }
        public string t_dest_country { get; set; }
        public string t_dest_institution_code { get; set; }
        public string t_dest_institution_name { get; set; }
        public string t_dest_account_number { get; set; }
        public string t_dest_account_name { get; set; }
        public string t_dest_person_first_name { get; set; }
        public string t_dest_person_last_name { get; set; }
        public string t_dest_entity_name { get; set; }
        public string Tran_Type { get; set; }
        public string uploader { get; set; }
        public Nullable<System.DateTime> uploaded { get; set; }
        public string batch_number { get; set; }
    }
}
