//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftAML_UpperLinkAPI.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Watchlist
    {
        public long Id { get; set; }
        public string RecordID { get; set; }
        public string Ind_Name { get; set; }
        public string Ind_aka { get; set; }
        public string Ind_fka { get; set; }
        public string Ind_nka { get; set; }
        public string EntityName { get; set; }
        public string Addr { get; set; }
        public string Ves { get; set; }
        public string Air { get; set; }
        public string PlaceBirth { get; set; }
        public string DateBirth { get; set; }
        public string City { get; set; }
        public string StateProvince { get; set; }
        public string nationality { get; set; }
        public string CountryCode { get; set; }
        public string ExtLinks { get; set; }
        public string IDType { get; set; }
        public string Source { get; set; }
        public string Remarks { get; set; }
    }
}
