// <auto-generated />
namespace SoftAML_UpperLinkAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addactiveaccount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addactiveaccount));
        
        string IMigrationMetadata.Id
        {
            get { return "202201252027559_add active account"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
